USB_VID = 0x239A
USB_PID = 0x80F4
USB_PRODUCT = "Magic 8 Badge"
USB_MANUFACTURER = "CrumpSpace"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"

CIRCUITPY__EVE = 1
CIRCUITPY_PICODVI = 1

CIRCUITPY_REQUIRE_I2C_PULLUPS = 0
